/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 64
#define YY_END_OF_BUFFER 65
static yyconst short int yy_acclist[420] =
    {   0,
       65,   63,   64,   61,   63,   64,   62,   64,   63,   64,
       63,   64,   53,   63,   64,   54,   63,   64,   52,   63,
       64,   63,   64,   46,   63,   64,   51,   63,   64,   50,
       63,   64,   49,   63,   64,   49,   63,   64,   49,   63,
       64,   49,   63,   64,   49,   63,   64,   49,   63,   64,
       49,   63,   64,   49,   63,   64,   49,   63,   64,   49,
       63,   64,   49,   63,   64,   49,   63,   64,   49,   63,
       64,   49,   63,   64,   49,   63,   64,   49,   63,   64,
       49,   63,   64,   55,   63,   64,   56,   63,   64,   57,
       63,   64,   58,   63,   64,   61,   48,   47,   59,   46,

       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   59,   45,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   60,   49,   49,   49,   49,   26,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   10,   49,   49,   49,   49,   49,   49,   49,   49,

       49,   49,   49,   49,   49,   49,   40,   49,   49,   49,
       49,   49,   49,   49,    4,   49,   49,   23,   49,   18,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   16,   49,   11,   49,
       49,   49,   38,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   27,   49,   49,   49,   49,   49,    3,
       49,   49,   49,   28,   49,   49,   49,   49,   49,   14,
       49,   49,   37,   49,   49,   49,   49,   49,   49,   49,
       15,   49,   49,   49,   49,   49,   49,   49,   49,   13,

       49,   49,   19,   49,   25,   49,   49,   22,   49,   49,
        2,   49,   24,   49,    1,   49,   49,   49,   49,   43,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   29,   49,   49,   49,   49,   41,
       49,   49,   49,   33,   49,   49,   49,   34,   49,   36,
       49,   49,   44,   49,   49,   49,   49,   49,   49,   49,
        5,   49,   49,   49,   49,   49,   31,   49,   17,   49,
       49,   39,   49,   49,   49,   49,    7,   49,   49,   49,
       49,   30,   49,   49,   49,   49,    9,   49,   49,   12,
       49,   49,    6,   49,   49,   49,   35,   49,   49,   49,

        8,   49,   49,   49,   42,   49,   49,   49,   49,   21,
       49,   49,   49,   49,   49,   32,   49,   20,   49
    } ;

static yyconst short int yy_accept[327] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   11,   13,   16,
       19,   22,   24,   27,   30,   33,   36,   39,   42,   45,
       48,   51,   54,   57,   60,   63,   66,   69,   72,   75,
       78,   81,   84,   87,   90,   93,   96,   97,   97,   98,
       98,   98,   99,   99,   99,  100,  100,  101,  102,  103,
      104,  105,  106,  107,  108,  109,  110,  111,  112,  113,
      114,  115,  116,  117,  118,  119,  120,  121,  122,  123,
      124,  125,  126,  127,  128,  129,  130,  131,  132,  133,
      133,  133,  134,  135,  136,  137,  138,  139,  140,  141,
      142,  143,  144,  145,  146,  147,  148,  149,  150,  151,

      152,  153,  154,  155,  156,  157,  158,  159,  160,  161,
      162,  163,  164,  165,  166,  167,  168,  169,  170,  171,
      172,  173,  174,  175,  176,  177,  178,  180,  181,  182,
      183,  184,  185,  186,  187,  188,  189,  190,  191,  192,
      194,  195,  196,  197,  198,  199,  200,  201,  202,  203,
      204,  205,  206,  207,  209,  210,  211,  212,  213,  214,
      215,  217,  218,  220,  222,  223,  224,  225,  226,  227,
      228,  229,  230,  231,  232,  233,  234,  235,  236,  237,
      238,  239,  240,  241,  242,  243,  244,  245,  246,  247,
      249,  251,  252,  253,  255,  256,  257,  258,  259,  260,

      261,  262,  263,  264,  266,  267,  268,  269,  270,  272,
      273,  274,  276,  277,  278,  279,  280,  282,  283,  285,
      286,  287,  288,  289,  290,  291,  293,  294,  295,  296,
      297,  298,  299,  300,  302,  303,  305,  307,  308,  310,
      311,  313,  315,  317,  318,  319,  320,  322,  323,  324,
      325,  326,  327,  328,  329,  330,  331,  332,  333,  334,
      335,  337,  338,  339,  340,  342,  343,  344,  346,  347,
      348,  350,  352,  353,  355,  356,  357,  358,  359,  360,
      361,  363,  364,  365,  366,  367,  369,  371,  372,  374,
      375,  376,  377,  379,  380,  381,  382,  384,  385,  386,

      387,  389,  390,  392,  393,  395,  396,  397,  399,  400,
      401,  403,  404,  405,  407,  408,  409,  410,  412,  413,
      414,  415,  416,  418,  420,  420
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    5,    6,
        7,    8,    1,    9,    1,   10,   11,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   13,   14,    1,
        1,    1,    1,    1,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   24,
       40,   41,   42,    1,   43,    1,   24,   24,   24,   24,

       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   44,    1,   45,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[46] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    1,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    1,
        1,    1,    3,    1,    1
    } ;

static yyconst short int yy_base[331] =
    {   0,
        0,    0,  352,  353,  349,  353,   42,   43,  353,  353,
      353,   39,   39,  353,  353,   36,   35,   38,   36,   35,
      315,    0,   41,   42,  330,   34,  316,  328,   52,   43,
      318,  316,  353,  353,  353,  353,  342,   68,  353,  340,
      337,  353,  338,  332,    0,  327,   64,    0,  309,  307,
      310,   51,  303,  315,  306,   58,  312,  297,  297,  312,
      300,   53,  312,  292,  292,  303,  307,  300,  292,   72,
      301,  288,  295,  291,  287,  283,  299,  279,  289,  303,
       83,    0,  298,  277,  282,  278,  273,  283,  283,  286,
      286,  286,  268,  279,  276,  278,  277,  278,  276,  265,

      274,  274,  257,  274,  265,  268,  252,  266,  249,  268,
      263,  246,  252,  244,  248,  254,  244,  248,  246,  250,
      254,  353,  237,  247,  232,  234,    0,  238,  241,  242,
      229,  248,  243,  242,  217,  240,  224,  234,  239,    0,
      233,  231,  219,  218,  219,  221,  226,  231,  224,  231,
      213,  229,  224,    0,  208,  222,  217,  206,  212,  194,
        0,  216,  192,    0,  191,  190,  204,  205,  212,  197,
      196,  210,  208,  202,  196,  201,  203,  192,  201,  176,
      181,  200,  180,  196,  186,  179,  184,  179,  182,    0,
        0,  181,  181,    0,  174,  167,  176,   78,  181,  184,

      168,  182,  167,    0,  177,  165,  168,  175,    0,  162,
      166,    0,  156,  169,  162,  171,    0,  171,    0,  145,
      164,  169,  170,  161,  153,    0,  150,  149,  158,  150,
      152,  149,  156,    0,  132,    0,    0,  155,  130,  144,
        0,    0,    0,  149,  137,  143,    0,  149,  150,  137,
      146,  130,  129,  147,  118,  128,  144,  123,  128,  122,
        0,  125,  137,  124,    0,  129,  132,    0,  118,  134,
        0,    0,  129,    0,  130,  127,  130,  112,  127,  127,
        0,  109,  115,  107,  112,    0,    0,  105,    0,  117,
      104,   95,    0,  107,   98,  102,    0,   87,  110,  107,

        0,   92,    0,  107,    0,   91,  105,    0,   94,  107,
        0,   91,   77,    0,   81,   88,   69,    0,   74,   85,
       71,   66,    0,    0,  353,  109,  112,   84,  115,  118
    } ;

static yyconst short int yy_def[331] =
    {   0,
      325,    1,  325,  325,  325,  325,  326,  327,  325,  325,
      325,  325,  325,  325,  325,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  325,  325,  325,  325,  325,  326,  325,  326,
      325,  325,  327,  329,  330,  325,  325,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  329,
      329,  330,  325,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,

      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  325,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,

      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,

      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,    0,  325,  325,  325,  325,  325
    } ;

static yyconst short int yy_nxt[399] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,    4,   11,    4,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   22,   22,   22,   22,   23,   24,   25,   26,   27,
       22,   28,   29,   30,   31,   32,   22,   22,   22,   33,
        4,   34,   22,   35,   36,   39,   44,   42,   46,   45,
       47,   49,   53,   51,   56,   62,   64,   58,   57,   54,
       59,   76,   50,   52,   65,   67,   55,   68,   71,   63,
       72,   39,   60,   46,   77,   47,   73,   92,   93,   87,
       99,   74,   40,   43,   88,   75,   48,  100,  108,  109,
       81,  324,  228,  122,  229,  230,  323,  231,  110,  322,

      232,  111,  321,  320,  319,  112,  318,  317,   40,   38,
       38,   38,   41,   41,   41,   80,   80,   80,   82,  316,
       82,  315,  314,  313,  312,  311,  310,  309,  308,  307,
      306,  305,  304,  303,  302,  301,  300,  299,  298,  297,
      296,  295,  294,  293,  292,  291,  290,  289,  288,  287,
      286,  285,  284,  283,  282,  281,  280,  279,  278,  277,
      276,  275,  274,  273,  272,  271,  270,  269,  268,  267,
      266,  265,  264,  263,  262,  261,  260,  259,  258,  257,
      256,  255,  254,  253,  252,  251,  250,  249,  248,  247,
      246,  245,  244,  243,  242,  241,  240,  239,  238,  237,

      236,  235,  234,  233,  227,  226,  225,  224,  223,  222,
      221,  220,  219,  218,  217,  216,  215,  214,  213,  212,
      211,  210,  209,  208,  207,  206,  205,  204,  203,  202,
      201,  200,  199,  198,  197,  196,  195,  194,  193,  192,
      191,  190,  189,  188,  187,  186,  185,  184,  183,  182,
      181,  180,  179,  178,  177,  176,  175,  174,  173,  172,
      171,  170,  169,  168,  167,  166,  165,  164,  163,  162,
      161,  160,  159,  158,  157,  156,  155,  154,  153,  152,
      151,  150,  149,  148,  147,  146,  145,  144,  143,  142,
      141,  140,  139,  138,  137,  136,  135,  134,  133,  132,

      131,  130,  129,  128,  127,  126,  125,  124,  123,   83,
       81,  121,  120,  119,  118,  117,  116,  115,  114,  113,
      107,  106,  105,  104,  103,  102,  101,   98,   97,   96,
       95,   94,   91,   90,   89,   86,   85,   84,   83,   81,
      325,   42,  325,   37,   79,   78,   70,   69,   66,   61,
       37,  325,    3,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325

    } ;

static yyconst short int yy_chk[399] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    7,   12,    8,   13,   12,
       13,   16,   18,   17,   19,   23,   24,   20,   19,   18,
       20,   30,   16,   17,   24,   26,   18,   26,   29,   23,
       29,   38,   20,   47,   30,   47,   29,   56,   56,   52,
       62,   29,    7,    8,   52,   29,  328,   62,   70,   70,
       81,  322,  198,   81,  198,  198,  321,  198,   70,  320,

      198,   70,  319,  317,  316,   70,  315,  313,   38,  326,
      326,  326,  327,  327,  327,  329,  329,  329,  330,  312,
      330,  310,  309,  307,  306,  304,  302,  300,  299,  298,
      296,  295,  294,  292,  291,  290,  288,  285,  284,  283,
      282,  280,  279,  278,  277,  276,  275,  273,  270,  269,
      267,  266,  264,  263,  262,  260,  259,  258,  257,  256,
      255,  254,  253,  252,  251,  250,  249,  248,  246,  245,
      244,  240,  239,  238,  235,  233,  232,  231,  230,  229,
      228,  227,  225,  224,  223,  222,  221,  220,  218,  216,
      215,  214,  213,  211,  210,  208,  207,  206,  205,  203,

      202,  201,  200,  199,  197,  196,  195,  193,  192,  189,
      188,  187,  186,  185,  184,  183,  182,  181,  180,  179,
      178,  177,  176,  175,  174,  173,  172,  171,  170,  169,
      168,  167,  166,  165,  163,  162,  160,  159,  158,  157,
      156,  155,  153,  152,  151,  150,  149,  148,  147,  146,
      145,  144,  143,  142,  141,  139,  138,  137,  136,  135,
      134,  133,  132,  131,  130,  129,  128,  126,  125,  124,
      123,  121,  120,  119,  118,  117,  116,  115,  114,  113,
      112,  111,  110,  109,  108,  107,  106,  105,  104,  103,
      102,  101,  100,   99,   98,   97,   96,   95,   94,   93,

       92,   91,   90,   89,   88,   87,   86,   85,   84,   83,
       80,   79,   78,   77,   76,   75,   74,   73,   72,   71,
       69,   68,   67,   66,   65,   64,   63,   61,   60,   59,
       58,   57,   55,   54,   53,   51,   50,   49,   46,   44,
       43,   41,   40,   37,   32,   31,   28,   27,   25,   21,
        5,    3,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325

    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "smpl_lexer.l"
#define INITIAL 0
#line 2 "smpl_lexer.l"
/*
 * SMPL (Space Mission Programming Language) Lexer
 * Flex specification file for lexical analysis
 * 
 * This lexer tokenizes SMPL source code and outputs tokens
 * in a format suitable for parsing with Bison.
 * 
 * Author: JIM2107054
 * Date: 2026
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Token type enumeration */
typedef enum {
    /* Program Structure */
    TOK_MISSION = 256,
    TOK_LANDING,
    TOK_LAUNCH,
    TOK_ABORT,
    
    /* Data Types */
    TOK_CARGO_INT,
    TOK_CARGO_FLOAT,
    TOK_CARGO_CHAR,
    TOK_CARGO_DOUBLE,
    TOK_VOID_SPACE,
    
    /* Declaration & Assignment */
    TOK_LOAD,
    TOK_STORE,
    TOK_CARGO_ARRAY,
    
    /* Arithmetic Operators */
    TOK_COMBINE,
    TOK_REDUCE,
    TOK_AMPLIFY,
    TOK_SPLIT,
    TOK_REMAINDER,
    TOK_BOOST,
    TOK_DEGRADE,
    
    /* Relational Operators */
    TOK_EXCEEDS,
    TOK_BELOW,
    TOK_EXCEEDS_OR_EQUAL,
    TOK_BELOW_OR_EQUAL,
    TOK_MATCHES,
    TOK_DIFFERS,
    
    /* Logical Operators */
    TOK_BOTH,
    TOK_EITHER,
    TOK_NEGATE,
    
    /* Conditional Statements */
    TOK_CHECK_IF,
    TOK_ELSE_CHECK,
    TOK_OTHERWISE,
    
    /* Switch-Case */
    TOK_PROTOCOL,
    TOK_SCENARIO,
    TOK_DEFAULT_PROTOCOL,
    
    /* Loop Constructs */
    TOK_ORBIT_WHILE,
    TOK_SEQUENCE,
    TOK_REPEAT,
    TOK_UNTIL,
    
    /* Loop Control */
    TOK_TERMINATE,
    TOK_SKIP,
    
    /* Functions */
    TOK_FUNCTION,
    TOK_RETURN_CARGO,
    
    /* I/O */
    TOK_RECEIVE,
    TOK_TRANSMIT,
    
    /* Literals & Identifiers */
    TOK_INTEGER,
    TOK_FLOAT_NUM,
    TOK_CHAR_LITERAL,
    TOK_STRING_LITERAL,
    TOK_IDENTIFIER,
    
    /* Punctuation */
    TOK_SEMICOLON,
    TOK_COLON,
    TOK_COMMA,
    TOK_LPAREN,
    TOK_RPAREN,
    TOK_LBRACKET,
    TOK_RBRACKET,
    TOK_LBRACE,
    TOK_RBRACE
} TokenType;

/* Line number tracking */
int line_num = 1;

/* Output file */
FILE *token_output;

/* Function to get token name */
const char* get_token_name(int token) {
    switch(token) {
        case TOK_MISSION: return "MISSION";
        case TOK_LANDING: return "LANDING";
        case TOK_LAUNCH: return "LAUNCH";
        case TOK_ABORT: return "ABORT";
        case TOK_CARGO_INT: return "CARGO_INT";
        case TOK_CARGO_FLOAT: return "CARGO_FLOAT";
        case TOK_CARGO_CHAR: return "CARGO_CHAR";
        case TOK_CARGO_DOUBLE: return "CARGO_DOUBLE";
        case TOK_VOID_SPACE: return "VOID_SPACE";
        case TOK_LOAD: return "LOAD";
        case TOK_STORE: return "STORE";
        case TOK_CARGO_ARRAY: return "CARGO_ARRAY";
        case TOK_COMBINE: return "COMBINE";
        case TOK_REDUCE: return "REDUCE";
        case TOK_AMPLIFY: return "AMPLIFY";
        case TOK_SPLIT: return "SPLIT";
        case TOK_REMAINDER: return "REMAINDER";
        case TOK_BOOST: return "BOOST";
        case TOK_DEGRADE: return "DEGRADE";
        case TOK_EXCEEDS: return "EXCEEDS";
        case TOK_BELOW: return "BELOW";
        case TOK_EXCEEDS_OR_EQUAL: return "EXCEEDS_OR_EQUAL";
        case TOK_BELOW_OR_EQUAL: return "BELOW_OR_EQUAL";
        case TOK_MATCHES: return "MATCHES";
        case TOK_DIFFERS: return "DIFFERS";
        case TOK_BOTH: return "BOTH";
        case TOK_EITHER: return "EITHER";
        case TOK_NEGATE: return "NEGATE";
        case TOK_CHECK_IF: return "CHECK_IF";
        case TOK_ELSE_CHECK: return "ELSE_CHECK";
        case TOK_OTHERWISE: return "OTHERWISE";
        case TOK_PROTOCOL: return "PROTOCOL";
        case TOK_SCENARIO: return "SCENARIO";
        case TOK_DEFAULT_PROTOCOL: return "DEFAULT_PROTOCOL";
        case TOK_ORBIT_WHILE: return "ORBIT_WHILE";
        case TOK_SEQUENCE: return "SEQUENCE";
        case TOK_REPEAT: return "REPEAT";
        case TOK_UNTIL: return "UNTIL";
        case TOK_TERMINATE: return "TERMINATE";
        case TOK_SKIP: return "SKIP";
        case TOK_FUNCTION: return "FUNCTION";
        case TOK_RETURN_CARGO: return "RETURN_CARGO";
        case TOK_RECEIVE: return "RECEIVE";
        case TOK_TRANSMIT: return "TRANSMIT";
        case TOK_INTEGER: return "INTEGER";
        case TOK_FLOAT_NUM: return "FLOAT_NUM";
        case TOK_CHAR_LITERAL: return "CHAR_LITERAL";
        case TOK_STRING_LITERAL: return "STRING_LITERAL";
        case TOK_IDENTIFIER: return "IDENTIFIER";
        case TOK_SEMICOLON: return "SEMICOLON";
        case TOK_COLON: return "COLON";
        case TOK_COMMA: return "COMMA";
        case TOK_LPAREN: return "LPAREN";
        case TOK_RPAREN: return "RPAREN";
        case TOK_LBRACKET: return "LBRACKET";
        case TOK_RBRACKET: return "RBRACKET";
        case TOK_LBRACE: return "LBRACE";
        case TOK_RBRACE: return "RBRACE";
        default: return "UNKNOWN";
    }
}

/* Function to output token */
void output_token(int token, const char* lexeme) {
    fprintf(token_output, "%-20s %-25s %d\n", get_token_name(token), lexeme, line_num);
}

/* Flex options */
/* Regular expression definitions */
#line 801 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 197 "smpl_lexer.l"


    /* ==================== KEYWORDS ==================== */

    /* Program Structure */
#line 958 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 326 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 353 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 202 "smpl_lexer.l"
{ output_token(TOK_MISSION, yytext); return TOK_MISSION; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 203 "smpl_lexer.l"
{ output_token(TOK_LANDING, yytext); return TOK_LANDING; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 204 "smpl_lexer.l"
{ output_token(TOK_LAUNCH, yytext); return TOK_LAUNCH; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 205 "smpl_lexer.l"
{ output_token(TOK_ABORT, yytext); return TOK_ABORT; }
	YY_BREAK
/* Data Types */
case 5:
YY_RULE_SETUP
#line 208 "smpl_lexer.l"
{ output_token(TOK_CARGO_INT, yytext); return TOK_CARGO_INT; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 209 "smpl_lexer.l"
{ output_token(TOK_CARGO_FLOAT, yytext); return TOK_CARGO_FLOAT; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 210 "smpl_lexer.l"
{ output_token(TOK_CARGO_CHAR, yytext); return TOK_CARGO_CHAR; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 211 "smpl_lexer.l"
{ output_token(TOK_CARGO_DOUBLE, yytext); return TOK_CARGO_DOUBLE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 212 "smpl_lexer.l"
{ output_token(TOK_VOID_SPACE, yytext); return TOK_VOID_SPACE; }
	YY_BREAK
/* Declaration & Assignment */
case 10:
YY_RULE_SETUP
#line 215 "smpl_lexer.l"
{ output_token(TOK_LOAD, yytext); return TOK_LOAD; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 216 "smpl_lexer.l"
{ output_token(TOK_STORE, yytext); return TOK_STORE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 217 "smpl_lexer.l"
{ output_token(TOK_CARGO_ARRAY, yytext); return TOK_CARGO_ARRAY; }
	YY_BREAK
/* Arithmetic Operators */
case 13:
YY_RULE_SETUP
#line 220 "smpl_lexer.l"
{ output_token(TOK_COMBINE, yytext); return TOK_COMBINE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 221 "smpl_lexer.l"
{ output_token(TOK_REDUCE, yytext); return TOK_REDUCE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 222 "smpl_lexer.l"
{ output_token(TOK_AMPLIFY, yytext); return TOK_AMPLIFY; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 223 "smpl_lexer.l"
{ output_token(TOK_SPLIT, yytext); return TOK_SPLIT; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 224 "smpl_lexer.l"
{ output_token(TOK_REMAINDER, yytext); return TOK_REMAINDER; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 225 "smpl_lexer.l"
{ output_token(TOK_BOOST, yytext); return TOK_BOOST; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 226 "smpl_lexer.l"
{ output_token(TOK_DEGRADE, yytext); return TOK_DEGRADE; }
	YY_BREAK
/* Relational Operators - longer patterns first */
case 20:
YY_RULE_SETUP
#line 229 "smpl_lexer.l"
{ output_token(TOK_EXCEEDS_OR_EQUAL, yytext); return TOK_EXCEEDS_OR_EQUAL; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 230 "smpl_lexer.l"
{ output_token(TOK_BELOW_OR_EQUAL, yytext); return TOK_BELOW_OR_EQUAL; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 231 "smpl_lexer.l"
{ output_token(TOK_EXCEEDS, yytext); return TOK_EXCEEDS; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 232 "smpl_lexer.l"
{ output_token(TOK_BELOW, yytext); return TOK_BELOW; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 233 "smpl_lexer.l"
{ output_token(TOK_MATCHES, yytext); return TOK_MATCHES; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 234 "smpl_lexer.l"
{ output_token(TOK_DIFFERS, yytext); return TOK_DIFFERS; }
	YY_BREAK
/* Logical Operators */
case 26:
YY_RULE_SETUP
#line 237 "smpl_lexer.l"
{ output_token(TOK_BOTH, yytext); return TOK_BOTH; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 238 "smpl_lexer.l"
{ output_token(TOK_EITHER, yytext); return TOK_EITHER; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 239 "smpl_lexer.l"
{ output_token(TOK_NEGATE, yytext); return TOK_NEGATE; }
	YY_BREAK
/* Conditional Statements */
case 29:
YY_RULE_SETUP
#line 242 "smpl_lexer.l"
{ output_token(TOK_CHECK_IF, yytext); return TOK_CHECK_IF; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 243 "smpl_lexer.l"
{ output_token(TOK_ELSE_CHECK, yytext); return TOK_ELSE_CHECK; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 244 "smpl_lexer.l"
{ output_token(TOK_OTHERWISE, yytext); return TOK_OTHERWISE; }
	YY_BREAK
/* Switch-Case - longer patterns first */
case 32:
YY_RULE_SETUP
#line 247 "smpl_lexer.l"
{ output_token(TOK_DEFAULT_PROTOCOL, yytext); return TOK_DEFAULT_PROTOCOL; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 248 "smpl_lexer.l"
{ output_token(TOK_PROTOCOL, yytext); return TOK_PROTOCOL; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 249 "smpl_lexer.l"
{ output_token(TOK_SCENARIO, yytext); return TOK_SCENARIO; }
	YY_BREAK
/* Loop Constructs */
case 35:
YY_RULE_SETUP
#line 252 "smpl_lexer.l"
{ output_token(TOK_ORBIT_WHILE, yytext); return TOK_ORBIT_WHILE; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 253 "smpl_lexer.l"
{ output_token(TOK_SEQUENCE, yytext); return TOK_SEQUENCE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 254 "smpl_lexer.l"
{ output_token(TOK_REPEAT, yytext); return TOK_REPEAT; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 255 "smpl_lexer.l"
{ output_token(TOK_UNTIL, yytext); return TOK_UNTIL; }
	YY_BREAK
/* Loop Control */
case 39:
YY_RULE_SETUP
#line 258 "smpl_lexer.l"
{ output_token(TOK_TERMINATE, yytext); return TOK_TERMINATE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 259 "smpl_lexer.l"
{ output_token(TOK_SKIP, yytext); return TOK_SKIP; }
	YY_BREAK
/* Functions */
case 41:
YY_RULE_SETUP
#line 262 "smpl_lexer.l"
{ output_token(TOK_FUNCTION, yytext); return TOK_FUNCTION; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 263 "smpl_lexer.l"
{ output_token(TOK_RETURN_CARGO, yytext); return TOK_RETURN_CARGO; }
	YY_BREAK
/* I/O */
case 43:
YY_RULE_SETUP
#line 266 "smpl_lexer.l"
{ output_token(TOK_RECEIVE, yytext); return TOK_RECEIVE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 267 "smpl_lexer.l"
{ output_token(TOK_TRANSMIT, yytext); return TOK_TRANSMIT; }
	YY_BREAK
/* ==================== LITERALS ==================== */
/* Float literal (must come before integer) */
case 45:
YY_RULE_SETUP
#line 272 "smpl_lexer.l"
{ output_token(TOK_FLOAT_NUM, yytext); return TOK_FLOAT_NUM; }
	YY_BREAK
/* Integer literal */
case 46:
YY_RULE_SETUP
#line 275 "smpl_lexer.l"
{ output_token(TOK_INTEGER, yytext); return TOK_INTEGER; }
	YY_BREAK
/* Character literal */
case 47:
YY_RULE_SETUP
#line 278 "smpl_lexer.l"
{ output_token(TOK_CHAR_LITERAL, yytext); return TOK_CHAR_LITERAL; }
	YY_BREAK
/* String literal */
case 48:
YY_RULE_SETUP
#line 281 "smpl_lexer.l"
{ output_token(TOK_STRING_LITERAL, yytext); return TOK_STRING_LITERAL; }
	YY_BREAK
/* ==================== IDENTIFIERS ==================== */
case 49:
YY_RULE_SETUP
#line 284 "smpl_lexer.l"
{ output_token(TOK_IDENTIFIER, yytext); return TOK_IDENTIFIER; }
	YY_BREAK
/* ==================== PUNCTUATION ==================== */
case 50:
YY_RULE_SETUP
#line 287 "smpl_lexer.l"
{ output_token(TOK_SEMICOLON, ";"); return TOK_SEMICOLON; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 288 "smpl_lexer.l"
{ output_token(TOK_COLON, ":"); return TOK_COLON; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 289 "smpl_lexer.l"
{ output_token(TOK_COMMA, ","); return TOK_COMMA; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 290 "smpl_lexer.l"
{ output_token(TOK_LPAREN, "("); return TOK_LPAREN; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 291 "smpl_lexer.l"
{ output_token(TOK_RPAREN, ")"); return TOK_RPAREN; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 292 "smpl_lexer.l"
{ output_token(TOK_LBRACKET, "["); return TOK_LBRACKET; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 293 "smpl_lexer.l"
{ output_token(TOK_RBRACKET, "]"); return TOK_RBRACKET; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 294 "smpl_lexer.l"
{ output_token(TOK_LBRACE, "{"); return TOK_LBRACE; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 295 "smpl_lexer.l"
{ output_token(TOK_RBRACE, "}"); return TOK_RBRACE; }
	YY_BREAK
/* ==================== COMMENTS ==================== */
/* Single-line comment */
case 59:
YY_RULE_SETUP
#line 299 "smpl_lexer.l"
{ /* Ignore single-line comments */ }
	YY_BREAK
/* Multi-line comment */
case 60:
YY_RULE_SETUP
#line 302 "smpl_lexer.l"
{ 
                            /* Count newlines in multi-line comments */
                            char *p = yytext;
                            while (*p) {
                                if (*p == '\n') line_num++;
                                p++;
                            }
                        }
	YY_BREAK
/* ==================== WHITESPACE ==================== */
case 61:
YY_RULE_SETUP
#line 312 "smpl_lexer.l"
{ /* Ignore whitespace */ }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 313 "smpl_lexer.l"
{ line_num++; }
	YY_BREAK
/* ==================== ERROR HANDLING ==================== */
case 63:
YY_RULE_SETUP
#line 316 "smpl_lexer.l"
{ 
                            fprintf(stderr, "Lexical Error at line %d: Unrecognized character '%s'\n", line_num, yytext);
                        }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 320 "smpl_lexer.l"
ECHO;
	YY_BREAK
#line 1401 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 326 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 326 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 325);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 320 "smpl_lexer.l"


/* Main function */
int main(int argc, char **argv) {
    if (argc < 2) {
        printf("Usage: %s <input_file> [output_file]\n", argv[0]);
        printf("  input_file  - SMPL source file to tokenize\n");
        printf("  output_file - (optional) Output file for tokens (default: stdout)\n");
        return 1;
    }
    
    /* Open input file */
    FILE *input = fopen(argv[1], "r");
    if (!input) {
        fprintf(stderr, "Error: Cannot open input file '%s'\n", argv[1]);
        return 1;
    }
    
    /* Open output file or use stdout */
    if (argc >= 3) {
        token_output = fopen(argv[2], "w");
        if (!token_output) {
            fprintf(stderr, "Error: Cannot open output file '%s'\n", argv[2]);
            fclose(input);
            return 1;
        }
    } else {
        token_output = stdout;
    }
    
    /* Print header */
    fprintf(token_output, "================================================================================\n");
    fprintf(token_output, "                    SMPL LEXICAL ANALYZER OUTPUT\n");
    fprintf(token_output, "================================================================================\n");
    fprintf(token_output, "Input file: %s\n", argv[1]);
    fprintf(token_output, "--------------------------------------------------------------------------------\n");
    fprintf(token_output, "%-20s %-25s %s\n", "TOKEN TYPE", "LEXEME", "LINE");
    fprintf(token_output, "--------------------------------------------------------------------------------\n");
    
    /* Set input */
    yyin = input;
    
    /* Tokenize */
    while (yylex() != 0);
    
    /* Print footer */
    fprintf(token_output, "--------------------------------------------------------------------------------\n");
    fprintf(token_output, "Lexical analysis completed. Total lines processed: %d\n", line_num);
    fprintf(token_output, "================================================================================\n");
    
    /* Cleanup */
    fclose(input);
    if (token_output != stdout) {
        fclose(token_output);
    }
    
    return 0;
}
