; ==========================================
; Three-Address Code (TAC)
; Generated by SMPL Compiler
; ==========================================

fuel = 100
counter = 0
temperature = 25.500000
scores = (null)
output "Countdown:"
i = 10
L0:
t0 = i > 0
if_false t0 goto L1
output i
t1 = i - 1
i = t1
goto L0
L1:
L2:
t2 = fuel > 0
t3 = fuel <= 100
t4 = t2 && t3
if_false t4 goto L3
t5 = fuel == 50
if_false t5 goto L4
output "Half fuel remaining"
L4:
t6 = fuel - 10
fuel = t6
t7 = fuel < 20
if_false t7 goto L6
L6:
goto L2
L3:
L8:
output counter
t8 = counter + 1
counter = t8
t9 = counter < 5
if_true t9 goto L8
status = 2
total = 0
j = 0
L10:
t10 = j < 3
if_false t10 goto L11
t11 = scores[j]
t12 = total + t11
total = t12
t13 = j + 1
j = t13
goto L10
L11:
output total
t14 = temperature > 20.000000
t15 = temperature < 30.000000
t16 = t14 && t15
if_false t16 goto L12
output "Temperature is comfortable"
goto L13
L12:
output "Temperature is extreme"
L13:

; ==========================================
