; ==========================================
; Three-Address Code (TAC)
; Intermediate Representation
; Generated by SMPL Compiler
; Source: samples\sample_proposal_test.smpl
; ==========================================

begin_program
fuel = 100
counter = 0
temperature = 25.5
declare_array int scores[3] = {85, 90, 78}
print "Countdown:"
t0 = i > 0
int i = 10  ; for init
L0:
if_false t0 goto L1
print i
goto L0
L1:
t1 = fuel > 0
t2 = fuel <= 100
t3 = t1 && t2
L2:
if_false t3 goto L3
t4 = fuel == 50
if_false t4 goto L4
print "Half fuel remaining"
L4:
L5:
t5 = fuel - 10
fuel = t5
t6 = fuel < 20
if_false t6 goto L6
break
L6:
L7:
goto L2
L3:
L8:
print counter
counter = counter + 1
t7 = counter < 5
if_true t7 goto L8
status = 2
switch status
case 1:
print "Status: Active"
break
case 2:
print "Status: Standby"
break
default:
print "Status: Unknown"
break
end_switch
total = 0
t8 = j < 3
int j = 0  ; for init
L9:
if_false t8 goto L10
t9 = scores[j]
t10 = total + t9
total = t10
goto L9
L10:
print total
t11 = temperature > 20.0
t12 = temperature < 30.0
t13 = t11 && t12
if_false t13 goto L11
print "Temperature is comfortable"
goto L12
L11:
print "Temperature is extreme"
L12:
return 0
end_program
